### ISSUE TITLE
Fix Python dependency caching in our Actions workflow

### ISSUE THREAD

**Issue by mukul-mehta** [lttkgp/C-3PO#87]
For now, we cache Python `pip` dependencies using:

```
    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
```
(Ref -> [test.yml](https://github.com/lttkgp/C-3PO/blob/master/.github/workflows/test.yml))

This doesn't seem to work for our use case and we need to fix it to properly cache dependencies
